version: "3.8"

services:
  spring-app:
    build:
      context: .
      args:
        SPRING_PROFILE: "dev"
    image: keim2152/spring-app/dev
    ports:
      - "8080:8080"
    restart: unless-stopped
