spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
  datasource:
    url: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL"
    hikari:
      maximum-pool-size: 1
    driver-class-name: org.h2.Driver
logging:
  level:
    root: info
    edu.bbte: debug
